version: "3"
services:
  node-app:
    restart: always
    build: ./node/
    environment:
      - NODE_ENV=production
    volumes:
      - ./backup:/usr/src/app/backup
    ports:
      - "7500:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db